// Auto-generated by scripts/collect-candidates.mjs — DO NOT EDIT BY HAND.
//
// Models waiting for approval in /admin → "מודלים לאישור". Empty is normal:
// it fills when a collection scan or a trending sweep finds something new.
// Items: 0

import type { Candidate } from "./candidates";

export const CANDIDATES: Candidate[] = [];
