// Auto-generated by scripts/collect-candidates.mjs — DO NOT EDIT BY HAND.
//
// Models waiting for approval in /admin → "מודלים לאישור". Nothing here is
// on the shop; the owner decides, one by one, in that tab.
// Items: 0
// Collected: 2026-10-04T10:38:01.049Z

import type { Candidate } from "./candidates";

export const CANDIDATES: Candidate[] = [];
