// Auto-generated by scripts/sync-collections.mjs — DO NOT EDIT BY HAND.
//
// Models waiting for approval in /admin → "מודלים לאישור". Nothing here is
// on the shop; the owner decides, one by one, in that tab.
// Items: 1
// Collected: 2026-09-20T15:40:05.720Z

import type { Candidate } from "./candidates";

export const CANDIDATES: Candidate[] = [
  {
    "id": "2094802",
    "title": "Cat Phone Stand",
    "slug": "cat-phone-stand",
    "license": "Standard Digital File License",
    "creator": "Hazel",
    "image": "https://makerworld.bblmw.com/makerworld/model/DSM00000002094802/design/2025-12-09_ae834e3585ba1.jpg?x-oss-process=image/resize,w_400/format,webp",
    "downloads": 12183,
    "likes": 3977,
    "grams": 38,
    "hours": 1.34,
    "colors": 1,
    "suggested": "home",
    "warnings": [],
    "via": "like",
    "tags": "猫 · 手机支架 · 办公室 · 办公桌 · 家用 · 好用"
  }
];
