// Auto-generated by scripts/import-makerworld.mjs — DO NOT EDIT BY HAND.
//
// Run `npm run import:makerworld` on a machine with internet access to fill
// this file from the collections listed in scripts/makerworld-sources.json.
// Until then it is empty and the site simply shows the hand-curated catalogue.

import type { ImportedModel } from "./imported";

export const IMPORTED_GENERATED: ImportedModel[] = [];

/** When the import last ran (ISO date), or null if it never has. */
export const IMPORTED_AT: string | null = null;
