// Auto-generated by scripts/fetch-videos.mjs — DO NOT EDIT BY HAND.
//
// The designer's clip for a model, served from this site. Product id → path.
// Items: 0
// Updated: never

export const LOCAL_VIDEOS: Record<string, string> = {};
