// Auto-generated by scripts/fetch-videos.mjs — DO NOT EDIT BY HAND.
//
// The designer's clip for a model, served from this site. Product id → path.
// Items: 13
// Updated: 2026-09-10T12:27:32.531Z

export const LOCAL_VIDEOS: Record<string, string> = {
  "mw-1271221": "img/catalog-video/1271221.mp4",
  "mw-2885863": "img/catalog-video/2885863.mp4",
  "mw-3076607": "img/catalog-video/3076607.mp4",
  "mw-3174552": "img/catalog-video/3174552.mp4",
  "mw-3229032": "img/catalog-video/3229032.mp4",
  "mw-3237023": "img/catalog-video/3237023.mp4",
  "mw-3239344": "img/catalog-video/3239344.mp4",
  "mw-3252105": "img/catalog-video/3252105.mp4",
  "mw-3258291": "img/catalog-video/3258291.mp4",
  "mw-3258776": "img/catalog-video/3258776.mp4",
  "mw-3260310": "img/catalog-video/3260310.mp4",
  "mw-3267559": "img/catalog-video/3267559.mp4",
  "mw-3268477": "img/catalog-video/3268477.mp4"
};
