// Auto-generated by scripts/fetch-images.mjs — DO NOT EDIT BY HAND.
//
// Remote photo URL → the copy of it stored in public/. Run
// `npm run fetch:images` after adding models.
// Images: 0

export const LOCAL_IMAGES: Record<string, string> = {

};
