// GENERATED by scripts/fetch-signals.mjs — do not edit by hand.
//
// What every shelf is ordered by. See lib/ranking.ts for how these become a
// position on the page, and the script's header for why each one is here.
//
// Empty until the script has run. That is a working state, not a broken one:
// lib/ranking.ts scores a model with no signals on its download count alone,
// which is exactly how the shelves were ordered before any of this existed.

export type ModelSignals = {
  downloads: number;
  likes: number;
  /** People who printed it — filament and hours, not a click. */
  prints: number;
  /** People who saved it to a collection — the closest thing to "I want this". */
  saves: number;
  comments: number;
  /** MakerWorld's own editors picked it. */
  picked: boolean;
  /** YYYY-MM-DD, or "" when the source did not say. */
  published: string;
  tags: string[];
  cats: string[];
};

export const SIGNALS: Record<string, ModelSignals> = {};

export const SIGNALS_AT = "";
