#!/usr/bin/env node
/**
 * The designer's clip of each model, hosted by us, small enough to hover.
 *
 *   npm run fetch:videos            # only models not checked yet
 *   npm run fetch:videos -- --all   # re-check every model
 *
 * A fidget that clicks and a flexi that bends sell themselves in two seconds of
 * video and not at all in a still. MakerWorld carries the designer's own clip
 * on some models (designExtension.design_video); this finds them, and turns a
 * 19MB 4K .mov into a ~1MB 480p muted MP4 — because this plays on hover, in a
 * grid, on a phone plan.
 *
 * Which models have one is cached in data/model-videos.json, so a second run
 * costs one request per NEW model rather than one per model. Requires ffmpeg;
 * without it the script says so and changes nothing.
 */
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { ROOT, c, sleep, fetchDetails } from "./lib/makerworld.mjs";

const CATALOGUE = path.join(ROOT, "lib", "imported.generated.ts");
const CACHE = path.join(ROOT, "data", "model-videos.json");
const OUT_DIR = path.join(ROOT, "public", "img", "catalog-video");
const MANIFEST = path.join(ROOT, "lib", "localVideos.generated.ts");

const hasFfmpeg = () => {
  try { execFileSync("ffmpeg", ["-version"], { stdio: "ignore" }); return true; }
  catch { return false; }
};

function ids() {
  const src = fs.readFileSync(CATALOGUE, "utf8");
  return [...new Set([...src.matchAll(/"id": "mw-(\d+)"/g)].map((m) => m[1]))];
}

function readCache() {
  if (!fs.existsSync(CACHE)) return {};
  try { return JSON.parse(fs.readFileSync(CACHE, "utf8")); } catch { return {}; }
}

async function main() {
  if (!hasFfmpeg()) {
    console.error(c.r("\n  אין ffmpeg — אי אפשר להמיר. התקן אותו ונסה שוב.\n"));
    process.exitCode = 1;
    return;
  }
  const all = process.argv.includes("--all");
  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.mkdirSync(path.dirname(CACHE), { recursive: true });

  const cache = readCache();
  const list = ids();
  const todo = all ? list : list.filter((id) => !(id in cache));
  console.log(c.b(`\n  ${list.length} מודלים · ${todo.length} לבדיקה\n`));

  let found = 0;
  for (const id of todo) {
    const d = await fetchDetails(id);
    await sleep(150);
    cache[id] = d?.video ?? null;
    if (d?.video) { found++; console.log(c.g(`  ✓ ${id}`) + c.d(`  ${d.title.slice(0, 46)}`)); }
  }
  if (todo.length) fs.writeFileSync(CACHE, `${JSON.stringify(cache, null, 2)}\n`, "utf8");
  console.log(c.d(`  ${found} חדשים עם וידאו`));

  // Download and shrink anything we do not already hold. Capped per run: a
  // 4K source takes real time to transcode, and a job that runs for an hour is
  // a job nobody lets finish. What is left is picked up by the next run.
  const MAX = Number(process.env.VIDEO_LIMIT || 30);
  let made = 0, failed = 0;
  for (const [id, url] of Object.entries(cache)) {
    if (!url) continue;
    if (made >= MAX) { console.log(c.d(`  עצירה אחרי ${MAX} — השאר בהרצה הבאה`)); break; }
    const out = path.join(OUT_DIR, `${id}.mp4`);
    if (fs.existsSync(out) && !all) continue;
    const tmp = path.join(OUT_DIR, `${id}.src`);
    try {
      const res = await fetch(url, { headers: { "user-agent": "Mozilla/5.0" } });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      fs.writeFileSync(tmp, Buffer.from(await res.arrayBuffer()));
      // 480p, silent, fast-start: a hover preview, not a feature film.
      execFileSync("ffmpeg", [
        "-y", "-loglevel", "error", "-i", tmp,
        "-an", "-vf", "scale=-2:480", "-c:v", "libx264",
        "-preset", "slow", "-crf", "30", "-pix_fmt", "yuv420p",
        "-movflags", "+faststart", out,
      ]);
      made++;
      console.log(c.g(`  → ${id}.mp4`) + c.d(`  ${(fs.statSync(out).size / 1e6).toFixed(1)}MB`));
    } catch (e) {
      failed++;
      console.log(c.y(`  ${id}: ${e.message}`));
    } finally {
      if (fs.existsSync(tmp)) fs.unlinkSync(tmp);
    }
  }

  // The manifest the shop reads. Only files that actually exist on disk.
  const have = fs.readdirSync(OUT_DIR).filter((f) => f.endsWith(".mp4")).sort();
  const map = Object.fromEntries(have.map((f) => [`mw-${f.replace(".mp4", "")}`, `img/catalog-video/${f}`]));
  fs.writeFileSync(
    MANIFEST,
    `// Auto-generated by scripts/fetch-videos.mjs — DO NOT EDIT BY HAND.\n` +
      `//\n// The designer's clip for a model, served from this site. Product id → path.\n` +
      `// Items: ${have.length}\n// Updated: ${new Date().toISOString()}\n\n` +
      `export const LOCAL_VIDEOS: Record<string, string> = ${JSON.stringify(map, null, 2)};\n`,
    "utf8",
  );
  const mb = have.reduce((a, f) => a + fs.statSync(path.join(OUT_DIR, f)).size, 0) / 1e6;
  console.log(c.g(`\n  ${have.length} סרטונים · ${mb.toFixed(1)}MB`) + (failed ? c.y(` · ${failed} נכשלו`) : "") + `\n`);
  void made;
}

main().catch((e) => {
  console.error(c.r(`\n  שגיאה: ${e.message}\n`));
  process.exitCode = 1;
});
